### PR TITLE
Added a pure_install function to match Module::Build.

### PR DESCRIPTION
**Pull request by matthewpersico**

### CODE REVIEW

**Comment by matthewpersico** [comment]
@Leont - sorry to be a pain, but can I get you to take a look at this? It would make life at my $job$ a bit easier. Thanks.

**Comment by matthewpersico** [comment]
@Leont - bump?

**Comment by matthewpersico** [comment]
@Leont - bump?

**Comment by Leont** [comment]
Back in 2005 `pure_install` was [added](https://github.com/Perl-Toolchain-Gang/Module-Build/commit/c4f6ed102bb5b2f8db43aa3eea4b78998c7a886b) for «when install starts writing to the file $(INSTALLARCHLIB)/perllocal.pod». This hasn't actually happened in the past 18 years, and I have no plans of implementing it to be honest, so the whole point is moot. I should probably update Module::Build's documentation to reflect this.

Just use `install` in both `Module::Build` and `Module::Build::Tiny`.

**Comment by Leont** [comment]
And much like `fake_install`, IMNSHO if we really need this to exist it ought to have been an argument (e.g. `--pure`) to `install` instead of a separate subcommand.

**Pull request closed without merging**
